#!/bin/sh

#Load the kernel modules for the assignment 5 part 2
case "$1" in
    start)
        echo "Loading kernel modules..."
        moddir="/lib/modules/$(uname -r)/extra"
        cd "$moddir" || exit 1
        /usr/bin/scull_load
        /usr/bin/module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Unloading kernel modules..."
        /usr/bin/module_unload faulty
        /usr/bin/scull_unload
        rmmod hello
        ;;
esac